site_name: Lua Classes for FiveM
nav:
  - 'Index': 'index.md'
  - 'Classes':
    - 'Utils':
      - 'Common':
        - 'string:split': 'utils/common/split.md'
        - 'string:startsWith': 'utils/common/startsWith.md'
        - 'string:endsWith': 'utils/common/endsWith.md'
        - 'string:trim': 'utils/common/trim.md'
        - 'table.build': 'utils/common/tablebuild.md'
        - 'table.fill': 'utils/common/tablefill.md'
        - 'table.dump': 'utils/common/tabledump.md'
        - '_type': 'utils/common/type.md'
        - 'warning': 'utils/common/warning.md'
      - 'Client':
        - 'TriggerServerCallback': 'utils/client/triggerservercallback.md'
        - 'RegisterClientCallback': 'utils/client/registerclientcallback.md'
        - 'ShowHelpNotification': 'utils/client/showhelpnotification.md'
        - 'ShowNotification': 'utils/client/shownotification.md'
        - 'TimeoutRequestModel': 'utils/client/timeoutrequestmodel.md'
      - 'Server':
        - 'TriggerClientCallback': 'utils/server/triggerclientcallback.md'
        - 'RegisterServerCallback': 'utils/server/registerservercallback.md'
    - 'Client':
      - 'Coords':
        - 'Init': 'coords/client/init.md'
        - 'AddBlip': 'coords/client/addblip.md'
        - 'UpdateX': 'coords/client/updatex.md'
        - 'UpdateY': 'coords/client/updatey.md'
        - 'UpdateZ': 'coords/client/updatez.md'
        - 'UpdateW': 'coords/client/updatew.md'
  - 'Credits': 'credits.md'

theme:
  name: material
  features:
    - navigation.instant
    - header.autohide
  palette:
    scheme: slate
    primary: deep orange

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
