site_name: Lua Classes for FiveM
nav:
  - 'Index': 'index.md'
  - 'Classes':
    - 'How to start': 'tutorial.md'
    - 'Hot to read the docs': 'read.md'
    - 'Utils':
      - 'Common':
        - 'string:split': 'utils/common/split.md'
        - 'string:startsWith': 'utils/common/startsWith.md'
        - 'string:endsWith': 'utils/common/endsWith.md'
        - 'string:trim': 'utils/common/trim.md'
        - 'table.build': 'utils/common/tablebuild.md'
        - 'table.fill': 'utils/common/tablefill.md'
        - 'table.dump': 'utils/common/tabledump.md'
        - '_type': 'utils/common/type.md'
        - 'warning': 'utils/common/warning.md'
      - 'Client':
        - 'TriggerServerCallback': 'utils/client/triggerservercallback.md'
        - 'RegisterClientCallback': 'utils/client/registerclientcallback.md'
        - 'ShowHelpNotification': 'utils/client/showhelpnotification.md'
        - 'ShowNotification': 'utils/client/shownotification.md'
        - 'TimeoutRequestModel': 'utils/client/timeoutrequestmodel.md'
        - 'TimeoutRequestAnim': 'utils/client/timeoutrequestanim.md'
      - 'Server':
        - 'TriggerClientCallback': 'utils/server/triggerclientcallback.md'
        - 'RegisterServerCallback': 'utils/server/registerservercallback.md'
    - 'Coords':
      - 'Common':
        - 'Init': 'coords/common/init.md'
        - 'UpdateX': 'coords/common/updatex.md'
        - 'UpdateY': 'coords/common/updatey.md'
        - 'UpdateZ': 'coords/common/updatez.md'
        - 'UpdateW': 'coords/common/updatew.md'
      - 'Client':
        - 'AddBlip': 'coords/client/addblip.md'
    - 'StateBag':
      - 'Common':
        - 'Init': 'statebag/common/init.md'
        - 'set': 'statebag/common/set.md'
        - 'get': 'statebag/common/get.md'
        - 'clear': 'statebag/common/clear.md'
        - 'clearAll': 'statebag/common/clearall.md'
    - 'Player':
      - 'Common':
        - 'Init': 'player/common/init.md'
    - 'Ped':
      - 'Common':
        - 'Init': 'ped/common/init.md'
    - 'Vehicle':
      - 'Common':
        - 'Init': 'vehicle/common/init.md'
  - 'Credits': 'credits.md'

theme:
  name: material
  features:
    - navigation.instant
    - header.autohide
  palette:
    scheme: slate
    primary: deep orange

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

site_dir: '../docs'

edit_uri: ''